language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
jobs:
  allow_failures:
    - stage: build
      os: osx
      env:
        - azure-osx

  include:
    - stage: build
      if: type = push
      os: linux
      dist: jammy
      sudo: required
      go: 1.22.x
      env:
        - azure-linux
      git:
        submodules: false # avoid cloning ethereum/tests
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - go run build/ci.go install -dlgo
        - echo $(ld -v) && echo $(gcc -v) && which go && go version
        - go run build/ci.go install -dlgo -arch 386
        - echo $(ld -v) && echo $(gcc -v) && which go && go version

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: "build/bin/geth"
  skip_cleanup: true
  on:
    tags: true
